import './globals.css';
import Head from 'next/head';
import Navbar from '../components/navbar/Navbar';
import Footer from '../components/footer/Footer.jsx';



export const metadata = {
  title: 'Monica-Fashion-Design',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body class="min-h-screen">
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
